/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/cluster/v1alpha1"
)

// FakeLabels implements LabelInterface
type FakeLabels struct {
	Fake *FakeClusterV1alpha1
}

var labelsResource = schema.GroupVersionResource{Group: "cluster.kubesphere.io", Version: "v1alpha1", Resource: "labels"}

var labelsKind = schema.GroupVersionKind{Group: "cluster.kubesphere.io", Version: "v1alpha1", Kind: "Label"}

// Get takes name of the label, and returns the corresponding label object, and an error if there is any.
func (c *FakeLabels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Label, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(labelsResource, name), &v1alpha1.Label{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Label), err
}

// List takes label and field selectors, and returns the list of Labels that match those selectors.
func (c *FakeLabels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LabelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(labelsResource, labelsKind, opts), &v1alpha1.LabelList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LabelList{ListMeta: obj.(*v1alpha1.LabelList).ListMeta}
	for _, item := range obj.(*v1alpha1.LabelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested labels.
func (c *FakeLabels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(labelsResource, opts))
}

// Create takes the representation of a label and creates it.  Returns the server's representation of the label, and an error, if there is any.
func (c *FakeLabels) Create(ctx context.Context, label *v1alpha1.Label, opts v1.CreateOptions) (result *v1alpha1.Label, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(labelsResource, label), &v1alpha1.Label{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Label), err
}

// Update takes the representation of a label and updates it. Returns the server's representation of the label, and an error, if there is any.
func (c *FakeLabels) Update(ctx context.Context, label *v1alpha1.Label, opts v1.UpdateOptions) (result *v1alpha1.Label, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(labelsResource, label), &v1alpha1.Label{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Label), err
}

// Delete takes name of the label and deletes it. Returns an error if one occurs.
func (c *FakeLabels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(labelsResource, name), &v1alpha1.Label{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLabels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(labelsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LabelList{})
	return err
}

// Patch applies the patch and returns the patched label.
func (c *FakeLabels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Label, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(labelsResource, name, pt, data, subresources...), &v1alpha1.Label{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Label), err
}
